INSERT INTO regencies (province_id, id, name)
VALUES (11, 1, 'KAB. ACEH SELATAN'),
       (11, 2, 'KAB. ACEH TENGGARA'),
       (11, 3, 'KAB. ACEH TIMUR'),
       (11, 4, 'KAB. ACEH TENGAH'),
       (11, 5, 'KAB. ACEH BARAT'),
       (11, 6, 'KAB. ACEH BESAR'),
       (11, 7, 'KAB. PIDIE'),
       (11, 8, 'KAB. ACEH UTARA'),
       (11, 9, 'KAB. SIMEULUE'),
       (11, 10, 'KAB. ACEH SINGKIL'),
       (11, 11, 'KAB. BIREUEN'),
       (11, 12, 'KAB. ACEH BARAT DAYA'),
       (11, 13, 'KAB. GAYO LUES'),
       (11, 14, 'KAB. ACEH JAYA'),
       (11, 15, 'KAB. NAGAN RAYA'),
       (11, 16, 'KAB. ACEH TAMIANG'),
       (11, 17, 'KAB. BENER MERIAH'),
       (11, 18, 'KAB. PIDIE JAYA'),
       (11, 71, 'KOTA BANDA ACEH'),
       (11, 72, 'KOTA SABANG'),
       (11, 73, 'KOTA LHOKSEUMAWE'),
       (11, 74, 'KOTA LANGSA'),
       (11, 75, 'KOTA SUBULUSSALAM'),
       (12, 1, 'KAB. TAPANULI TENGAH'),
       (12, 2, 'KAB. TAPANULI UTARA'),
       (12, 3, 'KAB. TAPANULI SELATAN'),
       (12, 4, 'KAB. NIAS'),
       (12, 5, 'KAB. LANGKAT'),
       (12, 6, 'KAB. KARO'),
       (12, 7, 'KAB. DELI SERDANG'),
       (12, 8, 'KAB. SIMALUNGUN'),
       (12, 9, 'KAB. ASAHAN'),
       (12, 10, 'KAB. LABUHANBATU'),
       (12, 11, 'KAB. DAIRI'),
       (12, 12, 'KAB. TOBA'),
       (12, 13, 'KAB. MANDAILING NATAL'),
       (12, 14, 'KAB. NIAS SELATAN'),
       (12, 15, 'KAB. PAKPAK BHARAT'),
       (12, 16, 'KAB. HUMBANG HASUNDUTAN'),
       (12, 17, 'KAB. SAMOSIR'),
       (12, 18, 'KAB. SERDANG BEDAGAI'),
       (12, 19, 'KAB. BATU BARA'),
       (12, 20, 'KAB. PADANG LAWAS UTARA'),
       (12, 21, 'KAB. PADANG LAWAS'),
       (12, 22, 'KAB. LABUHANBATU SELATAN'),
       (12, 23, 'KAB. LABUHANBATU UTARA'),
       (12, 24, 'KAB. NIAS UTARA'),
       (12, 25, 'KAB. NIAS BARAT'),
       (12, 71, 'KOTA MEDAN'),
       (12, 72, 'KOTA PEMATANGSIANTAR'),
       (12, 73, 'KOTA SIBOLGA'),
       (12, 74, 'KOTA TANJUNG BALAI'),
       (12, 75, 'KOTA BINJAI'),
       (12, 76, 'KOTA TEBING TINGGI'),
       (12, 77, 'KOTA PADANGSIDIMPUAN'),
       (12, 78, 'KOTA GUNUNGSITOLI'),
       (13, 1, 'KAB. PESISIR SELATAN'),
       (13, 2, 'KAB. SOLOK'),
       (13, 3, 'KAB. SIJUNJUNG'),
       (13, 4, 'KAB. TANAH DATAR'),
       (13, 5, 'KAB. PADANG PARIAMAN'),
       (13, 6, 'KAB. AGAM'),
       (13, 7, 'KAB. LIMA PULUH KOTA'),
       (13, 8, 'KAB. PASAMAN'),
       (13, 9, 'KAB. KEPULAUAN MENTAWAI'),
       (13, 10, 'KAB. DHARMASRAYA'),
       (13, 11, 'KAB. SOLOK SELATAN'),
       (13, 12, 'KAB. PASAMAN BARAT'),
       (13, 71, 'KOTA PADANG'),
       (13, 72, 'KOTA SOLOK'),
       (13, 73, 'KOTA SAWAHLUNTO'),
       (13, 74, 'KOTA PADANG PANJANG'),
       (13, 75, 'KOTA BUKITTINGGI'),
       (13, 76, 'KOTA PAYAKUMBUH'),
       (13, 77, 'KOTA PARIAMAN'),
       (14, 1, 'KAB. KAMPAR'),
       (14, 2, 'KAB. INDRAGIRI HULU'),
       (14, 3, 'KAB. BENGKALIS'),
       (14, 4, 'KAB. INDRAGIRI HILIR'),
       (14, 5, 'KAB. PELALAWAN'),
       (14, 6, 'KAB. ROKAN HULU'),
       (14, 7, 'KAB. ROKAN HILIR'),
       (14, 8, 'KAB. SIAK'),
       (14, 9, 'KAB. KUANTAN SINGINGI'),
       (14, 10, 'KAB. KEPULAUAN MERANTI'),
       (14, 71, 'KOTA PEKANBARU'),
       (14, 72, 'KOTA DUMAI'),
       (15, 1, 'KAB. KERINCI'),
       (15, 2, 'KAB. MERANGIN'),
       (15, 3, 'KAB. SAROLANGUN'),
       (15, 4, 'KAB. BATANGHARI'),
       (15, 5, 'KAB. MUARO JAMBI'),
       (15, 6, 'KAB. TANJUNG JABUNG BARAT'),
       (15, 7, 'KAB. TANJUNG JABUNG TIMUR'),
       (15, 8, 'KAB. BUNGO'),
       (15, 9, 'KAB. TEBO'),
       (15, 71, 'KOTA JAMBI'),
       (15, 72, 'KOTA SUNGAI PENUH'),
       (16, 1, 'KAB. OGAN KOMERING ULU'),
       (16, 2, 'KAB. OGAN KOMERING ILIR'),
       (16, 3, 'KAB. MUARA ENIM'),
       (16, 4, 'KAB. LAHAT'),
       (16, 5, 'KAB. MUSI RAWAS'),
       (16, 6, 'KAB. MUSI BANYUASIN'),
       (16, 7, 'KAB. BANYUASIN'),
       (16, 8, 'KAB. OGAN KOMERING ULU TIMUR'),
       (16, 9, 'KAB. OGAN KOMERING ULU SELATAN'),
       (16, 10, 'KAB. OGAN ILIR'),
       (16, 11, 'KAB. EMPAT LAWANG'),
       (16, 12, 'KAB. PENUKAL ABAB LEMATANG ILIR'),
       (16, 13, 'KAB. MUSI RAWAS UTARA'),
       (16, 71, 'KOTA PALEMBANG'),
       (16, 72, 'KOTA PAGAR ALAM'),
       (16, 73, 'KOTA LUBUK LINGGAU'),
       (16, 74, 'KOTA PRABUMULIH'),
       (17, 1, 'KAB. BENGKULU SELATAN'),
       (17, 2, 'KAB. REJANG LEBONG'),
       (17, 3, 'KAB. BENGKULU UTARA'),
       (17, 4, 'KAB. KAUR'),
       (17, 5, 'KAB. SELUMA'),
       (17, 6, 'KAB. MUKO MUKO'),
       (17, 7, 'KAB. LEBONG'),
       (17, 8, 'KAB. KEPAHIANG'),
       (17, 9, 'KAB. BENGKULU TENGAH'),
       (17, 71, 'KOTA BENGKULU'),
       (18, 1, 'KAB. LAMPUNG SELATAN'),
       (18, 2, 'KAB. LAMPUNG TENGAH'),
       (18, 3, 'KAB. LAMPUNG UTARA'),
       (18, 4, 'KAB. LAMPUNG BARAT'),
       (18, 5, 'KAB. TULANG BAWANG'),
       (18, 6, 'KAB. TANGGAMUS'),
       (18, 7, 'KAB. LAMPUNG TIMUR'),
       (18, 8, 'KAB. WAY KANAN'),
       (18, 9, 'KAB. PESAWARAN'),
       (18, 10, 'KAB. PRINGSEWU'),
       (18, 11, 'KAB. MESUJI'),
       (18, 12, 'KAB. TULANG BAWANG BARAT'),
       (18, 13, 'KAB. PESISIR BARAT'),
       (18, 71, 'KOTA BANDAR LAMPUNG'),
       (18, 72, 'KOTA METRO'),
       (19, 1, 'KAB. BANGKA'),
       (19, 2, 'KAB. BELITUNG'),
       (19, 3, 'KAB. BANGKA SELATAN'),
       (19, 4, 'KAB. BANGKA TENGAH'),
       (19, 5, 'KAB. BANGKA BARAT'),
       (19, 6, 'KAB. BELITUNG TIMUR'),
       (19, 71, 'KOTA PANGKAL PINANG'),
       (21, 1, 'KAB. BINTAN'),
       (21, 2, 'KAB. KARIMUN'),
       (21, 3, 'KAB. NATUNA'),
       (21, 4, 'KAB. LINGGA'),
       (21, 5, 'KAB. KEPULAUAN ANAMBAS'),
       (21, 71, 'KOTA BATAM'),
       (21, 72, 'KOTA TANJUNG PINANG'),
       (31, 1, 'KAB. ADM. KEP. SERIBU'),
       (31, 71, 'KOTA ADM. JAKARTA PUSAT'),
       (31, 72, 'KOTA ADM. JAKARTA UTARA'),
       (31, 73, 'KOTA ADM. JAKARTA BARAT'),
       (31, 74, 'KOTA ADM. JAKARTA SELATAN'),
       (31, 75, 'KOTA ADM. JAKARTA TIMUR'),
       (32, 1, 'KAB. BOGOR'),
       (32, 2, 'KAB. SUKABUMI'),
       (32, 3, 'KAB. CIANJUR'),
       (32, 4, 'KAB. BANDUNG'),
       (32, 5, 'KAB. GARUT'),
       (32, 6, 'KAB. TASIKMALAYA'),
       (32, 7, 'KAB. CIAMIS'),
       (32, 8, 'KAB. KUNINGAN'),
       (32, 9, 'KAB. CIREBON'),
       (32, 10, 'KAB. MAJALENGKA'),
       (32, 11, 'KAB. SUMEDANG'),
       (32, 12, 'KAB. INDRAMAYU'),
       (32, 13, 'KAB. SUBANG'),
       (32, 14, 'KAB. PURWAKARTA'),
       (32, 15, 'KAB. KARAWANG'),
       (32, 16, 'KAB. BEKASI'),
       (32, 17, 'KAB. BANDUNG BARAT'),
       (32, 18, 'KAB. PANGANDARAN'),
       (32, 71, 'KOTA BOGOR'),
       (32, 72, 'KOTA SUKABUMI'),
       (32, 73, 'KOTA BANDUNG'),
       (32, 74, 'KOTA CIREBON'),
       (32, 75, 'KOTA BEKASI'),
       (32, 76, 'KOTA DEPOK'),
       (32, 77, 'KOTA CIMAHI'),
       (32, 78, 'KOTA TASIKMALAYA'),
       (32, 79, 'KOTA BANJAR'),
       (33, 1, 'KAB. CILACAP'),
       (33, 2, 'KAB. BANYUMAS'),
       (33, 3, 'KAB. PURBALINGGA'),
       (33, 4, 'KAB. BANJARNEGARA'),
       (33, 5, 'KAB. KEBUMEN'),
       (33, 6, 'KAB. PURWOREJO'),
       (33, 7, 'KAB. WONOSOBO'),
       (33, 8, 'KAB. MAGELANG'),
       (33, 9, 'KAB. BOYOLALI'),
       (33, 10, 'KAB. KLATEN'),
       (33, 11, 'KAB. SUKOHARJO'),
       (33, 12, 'KAB. WONOGIRI'),
       (33, 13, 'KAB. KARANGANYAR'),
       (33, 14, 'KAB. SRAGEN'),
       (33, 15, 'KAB. GROBOGAN'),
       (33, 16, 'KAB. BLORA'),
       (33, 17, 'KAB. REMBANG'),
       (33, 18, 'KAB. PATI'),
       (33, 19, 'KAB. KUDUS'),
       (33, 20, 'KAB. JEPARA'),
       (33, 21, 'KAB. DEMAK'),
       (33, 22, 'KAB. SEMARANG'),
       (33, 23, 'KAB. TEMANGGUNG'),
       (33, 24, 'KAB. KENDAL'),
       (33, 25, 'KAB. BATANG'),
       (33, 26, 'KAB. PEKALONGAN'),
       (33, 27, 'KAB. PEMALANG'),
       (33, 28, 'KAB. TEGAL'),
       (33, 29, 'KAB. BREBES'),
       (33, 71, 'KOTA MAGELANG'),
       (33, 72, 'KOTA SURAKARTA'),
       (33, 73, 'KOTA SALATIGA'),
       (33, 74, 'KOTA SEMARANG'),
       (33, 75, 'KOTA PEKALONGAN'),
       (33, 76, 'KOTA TEGAL'),
       (34, 1, 'KAB. KULON PROGO'),
       (34, 2, 'KAB. BANTUL'),
       (34, 3, 'KAB. GUNUNGKIDUL'),
       (34, 4, 'KAB. SLEMAN'),
       (34, 71, 'KOTA YOGYAKARTA'),
       (35, 1, 'KAB. PACITAN'),
       (35, 2, 'KAB. PONOROGO'),
       (35, 3, 'KAB. TRENGGALEK'),
       (35, 4, 'KAB. TULUNGAGUNG'),
       (35, 5, 'KAB. BLITAR'),
       (35, 6, 'KAB. KEDIRI'),
       (35, 7, 'KAB. MALANG'),
       (35, 8, 'KAB. LUMAJANG'),
       (35, 9, 'KAB. JEMBER'),
       (35, 10, 'KAB. BANYUWANGI'),
       (35, 11, 'KAB. BONDOWOSO'),
       (35, 12, 'KAB. SITUBONDO'),
       (35, 13, 'KAB. PROBOLINGGO'),
       (35, 14, 'KAB. PASURUAN'),
       (35, 15, 'KAB. SIDOARJO'),
       (35, 16, 'KAB. MOJOKERTO'),
       (35, 17, 'KAB. JOMBANG'),
       (35, 18, 'KAB. NGANJUK'),
       (35, 19, 'KAB. MADIUN'),
       (35, 20, 'KAB. MAGETAN'),
       (35, 21, 'KAB. NGAWI'),
       (35, 22, 'KAB. BOJONEGORO'),
       (35, 23, 'KAB. TUBAN'),
       (35, 24, 'KAB. LAMONGAN'),
       (35, 25, 'KAB. GRESIK'),
       (35, 26, 'KAB. BANGKALAN'),
       (35, 27, 'KAB. SAMPANG'),
       (35, 28, 'KAB. PAMEKASAN'),
       (35, 29, 'KAB. SUMENEP'),
       (35, 71, 'KOTA KEDIRI'),
       (35, 72, 'KOTA BLITAR'),
       (35, 73, 'KOTA MALANG'),
       (35, 74, 'KOTA PROBOLINGGO'),
       (35, 75, 'KOTA PASURUAN'),
       (35, 76, 'KOTA MOJOKERTO'),
       (35, 77, 'KOTA MADIUN'),
       (35, 78, 'KOTA SURABAYA'),
       (35, 79, 'KOTA BATU'),
       (36, 1, 'KAB. PANDEGLANG'),
       (36, 2, 'KAB. LEBAK'),
       (36, 3, 'KAB. TANGERANG'),
       (36, 4, 'KAB. SERANG'),
       (36, 71, 'KOTA TANGERANG'),
       (36, 72, 'KOTA CILEGON'),
       (36, 73, 'KOTA SERANG'),
       (36, 74, 'KOTA TANGERANG SELATAN'),
       (51, 1, 'KAB. JEMBRANA'),
       (51, 2, 'KAB. TABANAN'),
       (51, 3, 'KAB. BADUNG'),
       (51, 4, 'KAB. GIANYAR'),
       (51, 5, 'KAB. KLUNGKUNG'),
       (51, 6, 'KAB. BANGLI'),
       (51, 7, 'KAB. KARANGASEM'),
       (51, 8, 'KAB. BULELENG'),
       (51, 71, 'KOTA DENPASAR'),
       (52, 1, 'KAB. LOMBOK BARAT'),
       (52, 2, 'KAB. LOMBOK TENGAH'),
       (52, 3, 'KAB. LOMBOK TIMUR'),
       (52, 4, 'KAB. SUMBAWA'),
       (52, 5, 'KAB. DOMPU'),
       (52, 6, 'KAB. BIMA'),
       (52, 7, 'KAB. SUMBAWA BARAT'),
       (52, 8, 'KAB. LOMBOK UTARA'),
       (52, 71, 'KOTA MATARAM'),
       (52, 72, 'KOTA BIMA'),
       (53, 1, 'KAB. KUPANG'),
       (53, 2, 'KAB TIMOR TENGAH SELATAN'),
       (53, 3, 'KAB. TIMOR TENGAH UTARA'),
       (53, 4, 'KAB. BELU'),
       (53, 5, 'KAB. ALOR'),
       (53, 6, 'KAB. FLORES TIMUR'),
       (53, 7, 'KAB. SIKKA'),
       (53, 8, 'KAB. ENDE'),
       (53, 9, 'KAB. NGADA'),
       (53, 10, 'KAB. MANGGARAI'),
       (53, 11, 'KAB. SUMBA TIMUR'),
       (53, 12, 'KAB. SUMBA BARAT'),
       (53, 13, 'KAB. LEMBATA'),
       (53, 14, 'KAB. ROTE NDAO'),
       (53, 15, 'KAB. MANGGARAI BARAT'),
       (53, 16, 'KAB. NAGEKEO'),
       (53, 17, 'KAB. SUMBA TENGAH'),
       (53, 18, 'KAB. SUMBA BARAT DAYA'),
       (53, 19, 'KAB. MANGGARAI TIMUR'),
       (53, 20, 'KAB. SABU RAIJUA'),
       (53, 21, 'KAB. MALAKA'),
       (53, 71, 'KOTA KUPANG'),
       (61, 1, 'KAB. SAMBAS'),
       (61, 2, 'KAB. MEMPAWAH'),
       (61, 3, 'KAB. SANGGAU'),
       (61, 4, 'KAB. KETAPANG'),
       (61, 5, 'KAB. SINTANG'),
       (61, 6, 'KAB. KAPUAS HULU'),
       (61, 7, 'KAB. BENGKAYANG'),
       (61, 8, 'KAB. LANDAK'),
       (61, 9, 'KAB. SEKADAU'),
       (61, 10, 'KAB. MELAWI'),
       (61, 11, 'KAB. KAYONG UTARA'),
       (61, 12, 'KAB. KUBU RAYA'),
       (61, 71, 'KOTA PONTIANAK'),
       (61, 72, 'KOTA SINGKAWANG'),
       (62, 1, 'KAB. KOTAWARINGIN BARAT'),
       (62, 2, 'KAB. KOTAWARINGIN TIMUR'),
       (62, 3, 'KAB. KAPUAS'),
       (62, 4, 'KAB. BARITO SELATAN'),
       (62, 5, 'KAB. BARITO UTARA'),
       (62, 6, 'KAB. KATINGAN'),
       (62, 7, 'KAB. SERUYAN'),
       (62, 8, 'KAB. SUKAMARA'),
       (62, 9, 'KAB. LAMANDAU'),
       (62, 10, 'KAB. GUNUNG MAS'),
       (62, 11, 'KAB. PULANG PISAU'),
       (62, 12, 'KAB. MURUNG RAYA'),
       (62, 13, 'KAB. BARITO TIMUR'),
       (62, 71, 'KOTA PALANGKARAYA'),
       (63, 1, 'KAB. TANAH LAUT'),
       (63, 2, 'KAB. KOTABARU'),
       (63, 3, 'KAB. BANJAR'),
       (63, 4, 'KAB. BARITO KUALA'),
       (63, 5, 'KAB. TAPIN'),
       (63, 6, 'KAB. HULU SUNGAI SELATAN'),
       (63, 7, 'KAB. HULU SUNGAI TENGAH'),
       (63, 8, 'KAB. HULU SUNGAI UTARA'),
       (63, 9, 'KAB. TABALONG'),
       (63, 10, 'KAB. TANAH BUMBU'),
       (63, 11, 'KAB. BALANGAN'),
       (63, 71, 'KOTA BANJARMASIN'),
       (63, 72, 'KOTA BANJARBARU'),
       (64, 1, 'KAB. PASER'),
       (64, 2, 'KAB. KUTAI KARTANEGARA'),
       (64, 3, 'KAB. BERAU'),
       (64, 7, 'KAB. KUTAI BARAT'),
       (64, 8, 'KAB. KUTAI TIMUR'),
       (64, 9, 'KAB. PENAJAM PASER UTARA'),
       (64, 11, 'KAB. MAHAKAM ULU'),
       (64, 71, 'KOTA BALIKPAPAN'),
       (64, 72, 'KOTA SAMARINDA'),
       (64, 74, 'KOTA BONTANG'),
       (65, 1, 'KAB. BULUNGAN'),
       (65, 2, 'KAB. MALINAU'),
       (65, 3, 'KAB. NUNUKAN'),
       (65, 4, 'KAB. TANA TIDUNG'),
       (65, 71, 'KOTA TARAKAN'),
       (71, 1, 'KAB. BOLAANG MONGONDOW'),
       (71, 2, 'KAB. MINAHASA'),
       (71, 3, 'KAB. KEPULAUAN SANGIHE'),
       (71, 4, 'KAB. KEPULAUAN TALAUD'),
       (71, 5, 'KAB. MINAHASA SELATAN'),
       (71, 6, 'KAB. MINAHASA UTARA'),
       (71, 7, 'KAB. MINAHASA TENGGARA'),
       (71, 8, 'KAB. BOLAANG MONGONDOW UTARA'),
       (71, 9, 'KAB. KEP. SIAU TAGULANDANG BIARO'),
       (71, 10, 'KAB. BOLAANG MONGONDOW TIMUR'),
       (71, 11, 'KAB. BOLAANG MONGONDOW SELATAN'),
       (71, 71, 'KOTA MANADO'),
       (71, 72, 'KOTA BITUNG'),
       (71, 73, 'KOTA TOMOHON'),
       (71, 74, 'KOTA KOTAMOBAGU'),
       (72, 1, 'KAB. BANGGAI'),
       (72, 2, 'KAB. POSO'),
       (72, 3, 'KAB. DONGGALA'),
       (72, 4, 'KAB. TOLI TOLI'),
       (72, 5, 'KAB. BUOL'),
       (72, 6, 'KAB. MOROWALI'),
       (72, 7, 'KAB. BANGGAI KEPULAUAN'),
       (72, 8, 'KAB. PARIGI MOUTONG'),
       (72, 9, 'KAB. TOJO UNA UNA'),
       (72, 10, 'KAB. SIGI'),
       (72, 11, 'KAB. BANGGAI LAUT'),
       (72, 12, 'KAB. MOROWALI UTARA'),
       (72, 71, 'KOTA PALU'),
       (73, 1, 'KAB. KEPULAUAN SELAYAR'),
       (73, 2, 'KAB. BULUKUMBA'),
       (73, 3, 'KAB. BANTAENG'),
       (73, 4, 'KAB. JENEPONTO'),
       (73, 5, 'KAB. TAKALAR'),
       (73, 6, 'KAB. GOWA'),
       (73, 7, 'KAB. SINJAI'),
       (73, 8, 'KAB. BONE'),
       (73, 9, 'KAB. MAROS'),
       (73, 10, 'KAB. PANGKAJENE KEPULAUAN'),
       (73, 11, 'KAB. BARRU'),
       (73, 12, 'KAB. SOPPENG'),
       (73, 13, 'KAB. WAJO'),
       (73, 14, 'KAB. SIDENRENG RAPPANG'),
       (73, 15, 'KAB. PINRANG'),
       (73, 16, 'KAB. ENREKANG'),
       (73, 17, 'KAB. LUWU'),
       (73, 18, 'KAB. TANA TORAJA'),
       (73, 22, 'KAB. LUWU UTARA'),
       (73, 24, 'KAB. LUWU TIMUR'),
       (73, 26, 'KAB. TORAJA UTARA'),
       (73, 71, 'KOTA MAKASSAR'),
       (73, 72, 'KOTA PARE PARE'),
       (73, 73, 'KOTA PALOPO'),
       (74, 1, 'KAB. KOLAKA'),
       (74, 2, 'KAB. KONAWE'),
       (74, 3, 'KAB. MUNA'),
       (74, 4, 'KAB. BUTON'),
       (74, 5, 'KAB. KONAWE SELATAN'),
       (74, 6, 'KAB. BOMBANA'),
       (74, 7, 'KAB. WAKATOBI'),
       (74, 8, 'KAB. KOLAKA UTARA'),
       (74, 9, 'KAB. KONAWE UTARA'),
       (74, 10, 'KAB. BUTON UTARA'),
       (74, 11, 'KAB. KOLAKA TIMUR'),
       (74, 12, 'KAB. KONAWE KEPULAUAN'),
       (74, 13, 'KAB. MUNA BARAT'),
       (74, 14, 'KAB. BUTON TENGAH'),
       (74, 15, 'KAB. BUTON SELATAN'),
       (74, 71, 'KOTA KENDARI'),
       (74, 72, 'KOTA BAU BAU'),
       (75, 1, 'KAB. GORONTALO'),
       (75, 2, 'KAB. BOALEMO'),
       (75, 3, 'KAB. BONE BOLANGO'),
       (75, 4, 'KAB. PAHUWATO'),
       (75, 5, 'KAB. GORONTALO UTARA'),
       (75, 71, 'KOTA GORONTALO'),
       (76, 1, 'KAB. PASANGKAYU'),
       (76, 2, 'KAB. MAMUJU'),
       (76, 3, 'KAB. MAMASA'),
       (76, 4, 'KAB. POLEWALI MANDAR'),
       (76, 5, 'KAB. MAJENE'),
       (76, 6, 'KAB. MAMUJU TENGAH'),
       (81, 1, 'KAB. MALUKU TENGAH'),
       (81, 2, 'KAB. MALUKU TENGGARA'),
       (81, 3, 'KAB. KEPULAUAN TANIMBAR'),
       (81, 4, 'KAB. BURU'),
       (81, 5, 'KAB. SERAM BAGIAN TIMUR'),
       (81, 6, 'KAB. SERAM BAGIAN BARAT'),
       (81, 7, 'KAB. KEPULAUAN ARU'),
       (81, 8, 'KAB. MALUKU BARAT DAYA'),
       (81, 9, 'KAB. BURU SELATAN'),
       (81, 71, 'KOTA AMBON'),
       (81, 72, 'KOTA TUAL'),
       (82, 1, 'KAB. HALMAHERA BARAT'),
       (82, 2, 'KAB. HALMAHERA TENGAH'),
       (82, 3, 'KAB. HALMAHERA UTARA'),
       (82, 4, 'KAB. HALMAHERA SELATAN'),
       (82, 5, 'KAB. KEPULAUAN SULA'),
       (82, 6, 'KAB. HALMAHERA TIMUR'),
       (82, 7, 'KAB. PULAU MOROTAI'),
       (82, 8, 'KAB. PULAU TALIABU'),
       (82, 71, 'KOTA TERNATE'),
       (82, 72, 'KOTA TIDORE KEPULAUAN'),
       (91, 3, 'KAB. JAYAPURA'),
       (91, 5, 'KAB. KEPULAUAN YAPEN'),
       (91, 6, 'KAB. BIAK NUMFOR'),
       (91, 10, 'KAB. SARMI'),
       (91, 11, 'KAB. KEEROM'),
       (91, 15, 'KAB. WAROPEN'),
       (91, 19, 'KAB. SUPIORI'),
       (91, 20, 'KAB. MAMBERAMO RAYA'),
       (91, 71, 'KOTA JAYAPURA'),
       (92, 1, 'KAB. SORONG'),
       (92, 2, 'KAB. MANOKWARI'),
       (92, 3, 'KAB. FAK FAK'),
       (92, 4, 'KAB. SORONG SELATAN'),
       (92, 5, 'KAB. RAJA AMPAT'),
       (92, 6, 'KAB. TELUK BINTUNI'),
       (92, 7, 'KAB. TELUK WONDAMA'),
       (92, 8, 'KAB. KAIMANA'),
       (92, 9, 'KAB. TAMBRAUW'),
       (92, 10, 'KAB. MAYBRAT'),
       (92, 11, 'KAB. MANOKWARI SELATAN'),
       (92, 12, 'KAB. PEGUNUNGAN ARFAK'),
       (92, 71, 'KOTA SORONG'),
       (93, 1, 'KAB. MERAUKE'),
       (93, 2, 'KAB. BOVEN DIGOEL'),
       (93, 3, 'KAB. MAPPI'),
       (93, 4, 'KAB. ASMAT'),
       (94, 1, 'KAB. NABIRE'),
       (94, 2, 'KAB. PUNCAK JAYA'),
       (94, 3, 'KAB. PANIAI'),
       (94, 4, 'KAB. MIMIKA'),
       (94, 5, 'KAB. PUNCAK'),
       (94, 6, 'KAB. DOGIYAI'),
       (94, 7, 'KAB. INTAN JAYA'),
       (94, 8, 'KAB. DEIYAI'),
       (95, 1, 'KAB. JAYAWIJAYA'),
       (95, 2, 'KAB. PEGUNUNGAN BINTANG'),
       (95, 3, 'KAB. YAHUKIMO'),
       (95, 4, 'KAB. TOLIKARA'),
       (95, 5, 'KAB. MAMBERAMO TENGAH'),
       (95, 6, 'KAB. YALIMO'),
       (95, 7, 'KAB. LANNY JAYA'),
       (95, 8, 'KAB. NDUGA');
