-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
--
-- CREATE TABLE IF NOT EXISTS user_profiles
-- (
--     user_id     UUID,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP    DEFAULT NOW(),
--
--     PRIMARY KEY (user_id),
--     FOREIGN KEY (user_id) REFERENCES users(id),
-- );