INSERT INTO trademark_status(id, status)
VALUES (1, "Diajukan"),
       (2, "Diterbitkan"),
       (3, "Ditarik"),
       (4, "Kadaluarsa");

INSERT INTO trademark_class(id, class, description)
VALUES (1, "Bahan Kimia",
        "Bahan kimia yang dipakai dalam industri, ilmu pengetahuan dan fotografi, maupun dalam pertanian, perkebunan, dan kehutanan; damar tiruan yang tidak diolah, plastik yang tidak diolah; pupuk; komposisi bahan pemadam api, sediaan pelunak dan pematri; zat-zat kimia untuk mengawetkan makanan; zat-zat penyamak perekat yang dipakai dalam industri."),
       (2, "Sediaan Cat",
        "Cat-cat, pernis-pernis; lak-Iak; bahan pencegah karat dan kelapukan kayu; bahan pewarna; pembetsa/pengering; bahan mentah, damar alam; logam dalam bentuk lembaran dan bubuk untuk para pelukis, penata dekor, pencetak dan seniman."),
       (3, "Kosmetik dan Sediaan Pembersih",
        "Sediaan pemutih dan za t-zat lainnya untuk mencuci; sediaan untuk membersihkan, mengkilapkan, membuang lemak dan menggosok; sabun; wangi-wangian, minyak atsiri; kosmetik, losion rambut; bahan-bahan pemelihara gigi."),
       (4, "Pelumas dan Bahan Bakar",
        "Minyak-minyak dan lemak-Iemak untuk industri; bahan pelumas; komposisi zat untuk menyerap, membasahi dan mengikat debu; bahan bakar (termasuk larutan hasil penyulingan untuk motor) dan bahan-bahan penerangan; lilin-lilin, sumbu-sumbu."),
       (5, "Farmasi",
        "Sediaan hasil farmasi, ilmu kehewanan dan saniter; bahan-bahan untuk berpantang makan/diet yang disesuaikan untuk pemakaian medis, makanan bayi; plester-plester, bahan-bahan pembalut; bahan-bahan untuk menambal gigi, bahan pembuat gigi palsu; pembasmi kuman; sediaan untuk membasmi binatang perusak, jamur, tumbuh-tumbuhan."),
       (6, "Barang Logam",
        "Logam-Iogam biasa dan campurannya; bahan bangunan dari logam; bangunan-bangunan dari logam yang dapat diangkut; bahan-bahan dari logam untuk jalan kereta api; kabel dan kawat-kawat dari logam biasa bukan untuk listrik; barang-barang besi, benda-benda kecil dari logam besi; pipa-pipa dan tabung-tabung dari logam; lemari-lemari besi barang-barang dari besi biasa yang tidak termasuk dalam kelas-kelas lain; semacam bijih bijihan."),
       (7, "Mesin",
        "Mesin-mesin dan mesin-mesin perkakas; motor-motor dan mesin-mesin (kecuali untuk kendaraan darat); kopeling mesin dan komponen transmisi (kecuali untuk kendaraan darat); perkakas pertanian; mesin tetas untuk telur."),
       (8, "Perkakas Tangan",
        "Alat-alat dan perkakas tangan (dijalankan dengan tangan) ; alat-alat pemotong; pedang; pisau silet"),
       (9, "Alat Listik dan Ilmiah",
        "Aparat dan instrumen ilmu pengetahuan, pelayaran, geodesi, listrik, fotografi, sinematografi, optik, timbang, ukur, sinyal, pemeriksaan (pengawasan) , penyelamatan dan pendidikan; aparat untuk merekam, mengirim atau mereproduksi suara atau gambar; pembawa data magnetik, disk perekam; mesin-mesin otomat dan mekanisme untuk aparat yang bekerja dengan memasukkan kepingan logam ke dalamnya; mesin kas, mesin hitung, peralatan pengolah data dan komputer; aparat pemadam kebakaran."),
       (10, "Peralatan Medis",
        "Aparat dan instrumen ilmu pengetahuan, pelayaran, geodesi, listrik, fotografi, sinematografi, optik, timbang, ukur, sinyal, pemeriksaan (pengawasan) , penyelamatan dan pendidikan; aparat untuk merekam, mengirim atau mereproduksi suara atau gambar; pembawa data magnetik, disk perekam; mesin-mesin otomat dan mekanisme untuk aparat yang bekerja dengan memasukkan kepingan logam ke dalamnya; mesin kas, mesin hitung, peralatan pengolah data dan komputer; aparat pemadam kebakaran."),
       (11, "Instalasi Penerangan",
        "Aparat/alat untuk keperluan penerangan, pemanasan, penghasil uap, pemasak, pendinginan, pengeringan, penyegaran udara, penyediaan air dan kebersihan."),
       (12, "Kendaraan", "Kendaraan-kendaraan; udara atau air, aparat/alat untuk bergerak di darat."),
       (13, "Senjata Api",
        "Senjata-senjata api; amunisi-amunisi dan proyektil-proyektil; bahan peledak; kembang api; petasan."),
       (14, "Perhiasan",
        "Logam-Iogam mulia serta campuran-campurannya dan benda-benda yang dibuat dari logam mulia atau yang dibalut dengan bahan itu, yang tidak termasuk dalam kelas-kelas lainnya; perhiasan, batu-batu mulia; jam-jam dan instrumen pengukur waktu."),
       (15, "Alat Musik", "Alat-alat musik."),
       (16, "Barang Kertas dan Cetakan",
        "Kertas, karton dan barang-barang yang terbuat dari bahan-bahan ini, yang tidak termasuk kelas-kelas lain; barang-barang cetakan; bahan-bahan untuk menjilid buku; potret-potret; alat tulis-menulis perekat untuk keperluan alat tulis-menulis atau rumah tangga alat-alat kesenian kwas untuk cat mesin tik dan keperluan kantor (kecuali perabot kantor); bahan pendidikan dan pengajaran (kecuali aparat-aparat); bahan-bahan plastik untuk pembungkus (yang tidak termasuk kelas-kelas lain), kartu-kartu main; huruf-huruf cetak; klise-klise."),
       (17, "Barang Karet",
        "Karet, getah-perca, getah, asbes, mika dan barang-barang terbuat dari bahan-bahan tersebut dan tidak termasuk kelas-kelas lain; plastik-plastik yang sudah berbentuk untuk digunakan da la m pembuatan barang; bahan-bahan untuk membungkus, merapatkan dan menyekat; pipa-pipa lentur, bukan dari logam."),
       (18, "Barang Kulit",
        "Kulit dan kulit imitasi, dan barang-barang terbuat dari bahan-bahan ini dan tidak termasuk dalam kelas-kelas lain; kulit-kulit halus binatang, kulit mentah; koper-koper dan tas-tas untuk tamasya; payung hujan, payung matahari dan tongkat-tongkat; cambuk-cambuk, pelana dan peralatan kuda dari kulit."),
       (19, "Bahan Bangunan Bukan Logam",
        "Bahan-bahan bangunan (bukan logam); pipa-pipa kaku bukan dari logam untuk bangunan; aspal, pek, bitumen; bangunan yang dapat dipindah pindah bukan dari logam; monumen-monumen, bukan dari logam."),
       (20, "Perabotan Rumah",
        "Perabot-perabot rumah, cermin-cermin, bingkai gambar; benda-benda (yang tidak termasuk dalam kelas-kelas lain) dari kayu, gabus, rumput, buluh, rotan, tanduk, tulang, gading, balein, kulit kerang, amber, kulit mutiara, tanah liat magnesium dan bahan-bahan penggantinya, atau dari plastik."),
       (21, "Peralatan Rumah Tangga dan Kaca",
        "Perkakas dan wadah-wadah untuk rumah tangga atau dapur (bukan dari logam mulia atau yang dilapisi logam mulia) sisir-sisir dan bunga-bunga karang; sikat-sikat (kecuali kwas-kwas); bahan pembuat sikat; benda-benda untuk membersihkan; wol; baja; kaca yang belum atau setengah dikerjakan (kecuali kaca yang dipakai dalam bangunan); gelas-gelas, porselin dan pecah belah dari tembikar yang tidak termasuk dalam kelas-kelas lain."),
       (22, "Tali dan Serat",
        "Tambang, tali, jala-jala, tenda-tenda, tirai, kain terpal, layar-Iayar, sak-sak dan kantong-kantong (yang tidak termasuk dalam kelas-kelas lain); bahan-bahan pelapis dan pengisi bantal (kecuali dari karet atau plastik); serat-serat kasar untuk pertenunan."),
       (23, "Benang untuk Tekstil", "Benang-benang untuk tekstil."),
       (24, "Kain",
        "Tekstil dan barang-barang tekstil, yang tidak termasuk dalam kelas-kelas lain; kasur tempat tidur dan meja."),
       (25, "Pakaian", "Pakaian, alas kaki, tutup kepala."),
       (26, "Renda, Sulam-menyulam",
        "Renda-renda dan sulaman-sulaman, pita-pita dan jalinan-jalinan dari pita; kancing-kancing kail dan mata kait, jarum-jarum pentul dan jarum-jarum; bunga-bunga buatan."),
       (27, "Penutup Lantai dan Karpet",
        "Karpet-karpet, permadani, keset berbahan anyaman, linoleum dan bahan-bahan lain untuk penutup ubin; hiasan-hiasan gantung dinding (bukan dari tekstil)."),
       (28, "Mainan dan Alat Olahraga",
        "Mainan-mainan; alat-alat senam dan olah-raga yang tidak termasuk kelas-kelas lain; hiasan pohon natal."),
       (29, "Daging dan Makanan Olahan",
        "Daging, ikan, unggas dan binatang buruan, saripati daging, buah-buahan dan sayuran yang diawetkan, dikeringkan dan dimasak, agar-agar; selai-selai; saus dari buah-buahan; telur, susu dan hasil-hasil produksi susu; minyak dan lemak-Iemak yang dapat dimakan."),
       (30, "Makanan Pokok",
        "Kopi, teh, kakao, gula, beras, tapioka, sagu, kopi olahan; tepung dan bahan baku terbuat dari gandum; roti, kue-kue dan kembang gula, minuman es; madu, air gula; ragi bubuk pengembang roti/kue; garam, moster; cuka, saus-saus (bumbu-bumbu) rempah-rempah, es, kecap, tauco, trasi, petis, krupuk, emping."),
       (31, "Produk Pertanian Alami",
        "Hasil-hasil produksi pertanian, perkebunan, kehutanan dan jenis-jenis gandum yang tidak termasuk dalam kelas-kelas lain; binatang-binatang hidup; buah-buahan dan sayuran segar; benih-benih; tanaman dan bunga-bunga alami; makanan hewan."),
       (32, "Minuman Ringan",
        "Bir dan berbagai jenis-jenis bir; air mineral dan air soda dan minuman bukan alkohol lainnya; minuman-minuman dari buah dan perasan buah; sirop-sirop dan sediaan-sediaan lain untuk membuat minuman."),
       (33, "Minuman Beralkohol", "Minum-minuman keras (kecuali bir)."),
       (34, "Tembakau dan Barang Keperluan Perokok", "Tembakau, barang-barang keperluan merokok; korek api."),
       (35, "Iklan dan Bisnis", "Periklanan; manajemen usaha; administrasi usaha; fungsi-fungsi kantor."),
       (36, "Asuransi dan Keuangan", "Asuransi; urusan keuangan; urusan moneter; urusan tanah dan bangunan."),
       (37, "Bangunan, Konstruksi, dan Reparasi",
        "Pembangunan gedung; perbaikan/renovasi; jasa-jasa pemasangan/instalatur."),
       (38, "Telekomunikasi", "Telekomunikasi"),
       (39, "Transportasi dan Penyimpanan",
        "Angkutan; pengemasan dan penyimpanan barang-barang; pengaturan perjalanan."),
       (40, "Penanganan Material", "Perawatan bahan-bahan."),
       (41, "Pendidikan dan Hiburan", "Pendidikan; pemberian pelatihan; hiburan; kegiatan olah-raga dan kebudayaan."),
       (42, "Komputer, Ilmiah, dan Hukum",
        "Jasa di bidang ilmu pengetahuan dan teknologi dan penelitian dan desain yang berkaitan; jasa untuk analisa dan penelitian di bidang ilmiah dan industri; desain dan pengembangan perangkat keras dan lunak komputer."),
       (43, "Hotel dan Restoran", "Penyediaan makanan dan minuman, akomodasi sementara."),
       (44, "Kedokteran, Kecantikan, dan Pertanian",
        "Perawatan medis, jasa-jasa pelayanan kedokteran hewan dan pertanian, jasa perawatan untuk manusia dan hewan, pertanian, hortikultural, jasa kehutanan."),
       (45, "Layanan Hukum/Legalitas",
        "Jasa-jasa pelayanan hukum, jasa pengamanan untuk perlindungan benda/barang dan individu, jasa perorangan dan sosial untuk memenuhi kebutuhan individu.");

INSERT INTO trademark_registration_status(id, status)
VALUES (1, "Ditolak"),
       (2, "Menunggu Konfirmasi"),
       (3, "Diajukan"),
       (4, "Diproses oleh DJKI"),
       (5, "Diterbitkan");
